Refactor: Replace Remaining '__x' Instances with '__id' #944
NVIDIA/stdexec pull request #1174
Opened 2023-12-17 09:10 UTC by ramanand-rv

### Description:
This PR addresses issue #944 by refactoring the codebase to replace all remaining instances of '__x' with the more descriptive '__id'. The changes aim to improve code readability and maintain consistency throughout the project.

### Changes Made
- Replaced '__x' with '__id' across the codebase, ensuring consistency in variable and function naming conventions.
- Checked and updated affected files in compliance with the project's style guide.
- Conducted comprehensive testing to verify that the changes do not introduce any new issue.

### Related Issue
Closes #944

Please review and merge this PR. Thank you!

2023-12-17 21:41 UTC, ericniebler requested changes
Thank you so much for taking a stab at this. The job is half-done. Replacing `__x` with `__id` is part of it. The other part involves changes to the class templates.

Code like this:

```c++
template <class TypeId>
struct Widget
  : WidgetInterface<stdexec::__t<TypeId>> {
  using Type = stdexec::__t<TypeId>;

  void foo(Type) override;
};

template <class Type>
Widget<stdexec::__x<Type>> makeWidget(Type t);
```

must change to code like this:

```c++
template <class TypeId>
struct Widget {
  using Type = stdexec::__t<TypeId>;

  struct __t                      // HERE
    : WidgetInterface<Type> {
    using __id = Widget<TypeId>;  // HERE
    void foo(Type) override;
  };
};

// HERE:
template <class Type>
stdexec::__t<Widget<stdexec::__id<Type>>> makeWidget(Type t);
```

This is all explained in the MAINTAINTERS.md [here](https://github.com/NVIDIA/stdexec/blob/main/MAINTAINERS.md#class-template-parameters)

2023-12-17 21:41 UTC, ericniebler commented on include/exec/__detail/__bwos_lifo_queue.hpp
> +#if defined(__id86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
It looks like your search and replace went awry here.

2023-12-17 21:41 UTC, ericniebler commented on include/exec/static_thread_pool.hpp
> +#include "./__detail/__idorshift.hpp"
Here too. You didn't test your changes?

2023-12-18 05:35 UTC, ramanand-rv commented
Thank you @ericniebler for the detailed explanation. Really sorry about the poor changes pushed earlier, I didn't go through the console, that was a blunder from my end. 
I went through the code base and realized that the changes requested for class templates already implemented in some places. I'd really appreciate if you can share the list of files where these changes are required to be added.

2023-12-19 00:00 UTC, ericniebler commented
You've already identified the places that need to change. Any place a class template was being instantiated with an argument wrapped in `__x`, that class template needs to be refactored.

2023-12-26 21:29 UTC, ericniebler commented
Closing. Feel free to reopen if and when you to come back to this.

2023-12-26 21:29 UTC, closed without merging